version: "3"
services:
  oscar:
    build: .
    stdin_open: true
    ports:
      - "10014:10014"
      - "10011:10011"
      - "10010:10010"
      - "10012:10012"
      - "10300:10300"
      - "10305:10305"
    restart: always
    environment:
      - INSTANCE_PRIVATE_IP=${INSTANCE_PRIVATE_IP}
      - INSTANCE_PUBLIC_IP=${INSTANCE_PUBLIC_IP}
