version: "3"
services:
  redis-cache:
    image: redis
    ports:
      - "6399:6379"
    restart: always
  admin-server:
    image: taxiconnect/general_administration:1.5
    stdin_open: true
    ports:
      - "10014:10014"
      - "10011:10011"
      - "10010:10010"
      - "10012:10012"
      - "10300:10300"
      - "10305:10305"
    restart: always