version: "3"
services:
  mongo:
    image: mongo:latest
    restart: always
  admin-server:
    depends_on: 
      - mongo
    image: admin-image:1.0
    build: .
    ports:
      - "10014:10014"
      - "10011:10011"
      - "10010:10010"
      - "10012:10012"
      - "10300:10300"
      - "10305:10305"
    restart: always
      
