
name: CI/CD Pipeline
on:
  push:
    branches: [ masterattend ]

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: latest
  continuous-deployment:
    needs: continous-integration
    runs-on: ubuntu-latest

    steps:
     # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Create CodeDeploy Deployment for Oscar
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Oscar \
            --deployment-group-name Oscar \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --file-exists-behavior OVERWRITE \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
